import pandas as pd

# task 1
survey1_names = ["self"]
survey1_subitems = ["List 10 specific ways that an average person may choose to identify themselves. Start with ""I am""."]

# task 2
survey2_names = ["creativity"]
survey2_items = ["Please write 10 words that are as different from each other as possible, in all meanings and uses of the words. Rules:\n1. Only single words.\n2. Only nouns (e.g., things, objects, concepts).\n3. No proper nouns (e.g., no specific people or places).\n4. No specialized vocabulary (e.g., no technical terms)."]

# task 3
survey3_names = ['inclusion_1', 'inclusion_2', 'inclusion_3', 'inclusion_4', 'inclusion_5', 'inclusion_6', 'inclusion_7', 'inclusion_8', 'inclusion_9', 'inclusion_10']
survey3_items = [
    "John is 29 years old. In graduate school, he falls in love with Elizabeth, 28 years old. They met each other in an advanced chemistry class, and graduated in the same year. I am trying to figure out why John fell in love with Elizabeth. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why John fell in love with Elizabeth. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text. \n1. whether or not they have shared interests.\n2. whether or not they belong to the same ethnicity. \n3. whether or not they like the same artist.\n4. whether or not it was raining on the day they met. \n5. whether or not John is from a small midwestern town. \n6. whether or not Elizabeth is rich. \n7. whether or not John's mother is nice. \n8. whether or not Elizabeth is an only child. \n9. whether or not their friends are dog people. \n10. whether or not they are blondes." , 

    "Amy is in Sociology class, and the professor of the class assigns the students to read a book on social structures in history, but Amy does not read the book. I am trying to figure out why Amy did not read the book. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Amy did not read the book. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text. \n1. Whether or not Amy is a jealous person.\n2. Whether or not Amy thought the professor’s teaching methods are boring.\n3. Whether or not Amy believes mathematics is flawed.\n4. Whether or not Amy has an older stepbrother.\n5. Whether or not Amy finds the professor’s voice annoying.\n6. Whether or not Amy had a bad day on the first day of class.\n7. Whether or not the author of the book believes in ghosts.\n8. Whether or not Amy likes the cold weather.\n9. Whether or not Amy has friends in that class.\n10. Whether or not the professor of the class is religious.", 
    
    "Todd, age 23, goes to the gym every night after work to work out.  I am trying to figure out why Todd goes to the gym every night. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Todd might go every night. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text.\n1. Whether or not Todd is married.\n2. Whether or not Todd enjoys dancing.\n3. Whether or not the gym owner is a woman.\n4. Whether or not it’s Todd lives in a hot city.\n5. Whether or not Todd likes his day job.\n6. Whether or not Todd is an introverted person.\n7. Whether or not Todd’s coworkers like cats.\n8. Whether or not Todd likes to read books.\n9. Whether or not Todd is a software engineer.\n10. Whether or not the gym is crowded at night.",

    "Melanie and Janine are college friends. On a rainy day in November, Janine tells Melanie that she no longer wants to be friends with Melanie. I am trying to figure out why Janine does not want to be friends with Melanie anymore. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Janine no longer wants to be Melanie’s friend. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text.\n1. Whether or not Melanie was born in October.\n2. Whether or not Melanie got worse grades than Janine in college.\n3. Whether or not they had different hobbies.\n4. Whether or not Melanie became a vegetarian.\n5. Whether or not Janine was responsible for her sick mom.\n6. Whether or they had the same beliefs about European art history.\n7. Whether or not Melanie read the Bible.\n8. Whether or not Melanie had a mental illness.\n9. Whether or not they worked together in the same subject two years ago.\n10. Whether or not Melanie was gay.",

    "Martin is Joshua’s father. Joshua is 16 years old. One day Martin gifted Joshua a book about social relations and how to be a good public speaker. I am trying to figure out why Martin gave Joshua the book as a present. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Martin gifted Joshua the book. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text.\n1. Whether or not it was a religious holiday.\n2. Whether or not Martin was trying to teach Joshua a lesson about making his bed.\n3. Whether or not Joshua had unprotected sex with his girlfriend.\n4. Whether or not Martina and Joshua had an argument about renovating the house.\n5. Whether or not Joshua enjoys video games.\n6. Whether or not Martin is a war veteran.\n7. Whether or not Joshua frequently helps with cooking.\n8. Whether or not Joshua’s parents are divorced.\n9. Whether or not Joshua has siblings.\n10. Whether or not Joshua owns a car.",

    "Tim was walking on the street when he found a cat. Tim decides to bring the cat home and keep the cat as a pet. Tim named the cat “Leo”.  I am trying to figure out why Tim adopted the cat. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Tim decided to adopt the cat and name it Leo. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text. \n1. Whether or not the cat was young. \n2. Whether or not the cat catches birds. \n3. Whether or not Tim is an artist. \n4. Whether or not the cat is cute. \n5. Whether or not it was snowing outside. \n6. Whether or not Tim’s roommate likes dogs. \n7. Whether or not Tim’s sister has a cat. \n8. Whether or not Tim already has a lot of pets. \n9. Whether or not Tim is a medical doctor. \n10. Whether or not Tim had a dream about a lion eating him alive last night.",
    
    "Tony receives a book from Allen. Tony decides not to keep the book and drops the book off at a thrift store.  I am trying to figure out why Tony did not keep the book. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Tony decides not to keep the book. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text.\n1. Whether Tony and Allen are from London.\n2. Whether or not Tony found the book interesting.\n3. Whether or not Tony is a philosopher.\n4. Whether or not Tony and Allen both like plants.\n5. Whether or not the book was made of recycled paper.\n6. Whether or not Tony likes donating to charity.\n7. Whether or not Tony likes playing board games.\n8. Whether or not Tony is unemployed.\n9. Whether or not Allen and Tony share similar interests.\n10. Whether or not Allen is a professional soccer player.",

    "One day, Ryan and Riley both go to get cosmetic surgeries. Ryan and Riley are friends.  I am trying to figure out why Ryan and Riley decided to get cosmetic surgeries. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Ryan and Riley got their ears pierced. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text. \n1. Whether or not Ryan and Riley are from Paris. \n2. Whether or not they care about the latest fashion trends. \n3. Whether or not they have conservative parents. \n4. Whether or not they regularly wear jewelry. \n5. Whether or not they want to be popular at school. \n6. Whether or not they are artistic. \n7. Whether or not they are selfish. \n8. Whether or not Riley is too scared to do it alone. \n9. Whether or not they like birds. \n10. Whether or not Ryan likes spending time with Riley.",

    "Jamie and Julian are hiking down a trail. Suddenly, Jamie reaches over and holds Julian’s hand.  I am trying to figure out why Jamie suddenly held Julian’s hand. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Jamie took Julian’s hand. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text. \n1. Whether or not Julian is rich. \n2. Whether or not Julian and Jamie are creative. \n3. Whether or not Jamie tripped over a rock. \n4. Whether or not Jamie enjoys hiking. \n5. Whether or not it was snowing outside. \n6. Whether or not Julian enjoys watching the sunset. \n7. Whether or not the birds were singing. \n8. Whether or not Julian was tall. \n9. Whether or not Julian was sad. \n10. Whether or not Jamie’s father is an honorable person.",

    "Max and Sam are married. After a few years, Max and Sam decide to end their marriage.  I am trying to figure out why they ended their marriage. I will now list 10 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why Max and Sam decided to end their romantic relationship. Please only say either 'Relevant' or 'Irrelevant', and don't give additional text. \n1. Whether or not they got are attractive. \n2. Whether or not they have the same family name. \n3. Whether or not they enjoy the same activities. \n4. Whether or not Max is allergic to cats. \n5. Whether or not there was a lunar eclipse that night. \n6. Whether or not Sam’s friends enjoy partying. \n7. Whether or not they have similar personalities. \n8. Whether or not they are both night owls. \n9. Whether or not Sam’s family is rich. \n10. Whether or not Max’s father is religious."
    ]

# task 4
survey4_names = ['attribution_1', 'attribution_2', 'attribution_3', 'attribution_4', 'attribution_5', 'attribution_6']
survey4_items = [
    "Sara Martin is a top executive at a pharmaceutical company that recently developed a new and expensive drug for treating malaria. Shortly after the company developed the drug, there was a significant outbreak of malaria in Africa. In response, Sara Martin decided to donate a lot of medicine to the countries in Africa needing assistance. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Sara Martin (such as her character, attitude, or temperament) influenced her behavior (donatin \nmalaria medicine to countries in Africa needing assistance) \n2. Features of the environment that surround Sara Martin (such as the atmosphere, social norms, or other contextua \nfactors) influenced her behavior (donating malaria medicine to countries in Africa needing assistance) \n3. Sara Martin would have acted differently if her features (such as her character, attitude, or temperament) ha \nbeen different \n4. Sara Martin would have acted differently if features of the environment that surround her (such as th \natmosphere, social norms, or other contextual factors) had been different \n5. The executive, Sara Martin, is conscientious \n6. The executive, Sara Martin, is immoral \n7. The executive, Sara Martin, is evil \n8. The executive, Sara Martin, is honest \n9. The executive, Sara Martin, is respectable \n10. The executive, Sara Martin, is manipulative \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.",
                 
"A doctor at a large hospital, David Conner, provides treatment for many people in the Baltimore area. He specializes in surgeries and performs them often. Recently, a woman underwent routine surgery to treat her stomach ulcers. During the surgery, an avoidable mistake was made and the woman died. David Conner concealed the mistake and told the woman’s family that she died of a heart attack. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of David Conner (such as his character, attitude, or temperament) influenced his behavior (concealing \nan avoidable mistake that caused the death of a patient). \n2. Features of the environment that surround David Conner (such as the atmosphere, social norms, or other \ncontextual factors) influenced his behavior (concealing an avoidable mistake that caused the death of a patient). \n3. David Conner would have acted differently if his features (such as his character, attitude, or temperament) had \nbeen different. \n4. David Conner would have acted differently if features of the environment that surround him (such as the \natmosphere, social norms, or other contextual factors) had been different. \n5. The doctor, David Conner, is conscientious. \n6. The doctor, David Conner, is immoral. \n7. The doctor, David Conner, is evil. \n8. The doctor, David Conner, is honest. \n9. The doctor, David Conner, is respectable. \n10. The doctor, David Conner, is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.",

"Emma Peterson, a prominent banker at a large bank in Boston, is well known in the local community. The bank lost a lot of money in the stock market, but she did not reveal the loss to the company’s shareholders. Instead, Emma Peterson reported a sizable profit at the annual meeting of the shareholders. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Emma Peterson (such as her character, attitude, or temperament) influenced her behavior (concealing \na sizable loss in the stock market from shareholders). \n2. Features of the environment that surround Emma Peterson (such as the atmosphere, social norms, or other \ncontextual factors) influenced her behavior (concealing a sizable loss in the stock market from shareholders). \n3. Emma Peterson would have acted differently if her features (such as her character, attitude, or temperament) had \nbeen different. \n4. Emma Peterson would have acted differently if features of the environment that surround her (such as the \natmosphere, social norms, or other contextual factors) had been different. \n5. The banker, Emma Peterson, is conscientious. \n6. The banker, Emma Peterson, is immoral. \n7. The banker, Emma Peterson, is evil. \n8. The banker, Emma Peterson, is honest. \n9. The banker, Emma Peterson is respectable. \n10. The banker, Emma Peterson is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.",

"Steve Jensen is the president of an electric company in Oregon that provides electricity to several large cities in the state. Last year, the winter in Portland was very cold and there were three unexpected snowstorms. Many elderly people in Portland could not afford to pay expensive electricity bills. In response, Steve Jensen decided to provide free electricity to disadvantaged elderly people during the winter months. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Steve Jensen (such as his character, attitude, or temperament) influenced his behavior (providing \nfree electricity to disadvantaged elderly people). \n2. Features of the environment that surround Steve Jensen (such as the atmosphere, social norms, or other \ncontextual factors) influenced his behavior (providing free electricity to disadvantaged elderly people). \n3. Steve Jensen would have acted differently if his features (such as his character, attitude, or temperament) had \nbeen different. \n4. Steve Jensen would have acted differently if features of the environment that surround him (such as the \natmosphere, social norms, or other contextual factors) had been different. \n5. The president, Steve Jensen, is conscientious. \n6. The president, Steve Jensen, is immoral. \n7. The president, Steve Jensen, is evil. \n8. The president, Steve Jensen, is honest. \n9. The president, Steve Jensen is respectable. \n10. The president, Steve Jensen is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.",

"A pitcher for a professional baseball team, Tom Lyons, lost several games in the beginning of the season. Instead of spending extra time practicing, he used performance-enhancing drugs for the rest of the regular season. Tom Lyons continued to use the drugs, even though the use of performance-enhancing drugs is illegal and considered to be cheating. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Tom Lyons (such as his character, attitude, or temperament) influenced his behavior (using \nperformance-enhancing drugs). \n2. Features of the environment that surround Tom Lyons (such as the atmosphere, social norms, or other contextual \nfactors) influenced his behavior (using performance-enhancing drugs). \n3. Tom Lyons would have acted differently if his features (such as his character, attitude, or temperament) had \nbeen different. \n4. Tom Lyons would have acted differently if features of the environment that surround him (such as the atmosphere, \nsocial norms, or other contextual factors) had been different. \n5. The pitcher, Tom Lyons, is conscientious. \n6. The pitcher, Tom Lyons is immoral. \n7. The pitcher, Tom Lyons is evil. \n8. The pitcher, Tom Lyons is honest. \n9. The pitcher, Tom Lyons, is respectable. \n10. The pitcher, Tom Lyons, is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.",

"A popular rock singer, Gina Gold, spent twelve months traveling all over the country on a big concert tour. At the end of the tour, she performed four additional charity concerts to raise money for New York City’s youth organizations. Gina Gold raised almost one million dollars for the youth organizations. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Gina Gold (such as her character, attitude, or temperament) influenced her behavior (performing \ncharity concerts to raise money for youth organizations). \n2. Features of the environment that surround Gina Gold (such as the atmosphere, social norms, or other contextual \nfactors) influenced her behavior (performing charity concerts to raise money for youth organizations). \n3. Gina Gold would have acted differently if her features (such as her character, attitude, or temperament) had \nbeen different. \n4. Gina Gold would have acted differently if features of the environment that surround her (such as the atmosphere, \nsocial norms, or other contextual factors) had been different. \n5. The singer, Gina Gold, is conscientious. \n6. The singer, Gina Gold, is immoral. \n7. The singer, Gina Gold, is evil. \n8. The singer, Gina Gold, is honest. \n9. The singer, Gina Gold, is respectable. \n10. The singer, Gina Gold, is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text."
]

# task 5
survey5_names = ['triad']
survey5_items = ["In the following lists, among the three things listed together, please indicate which two of the three are most closely related. \n1.  Seagull, Sky, Dog \n2.  Black, White, Blue \n3.  Doctor, Teacher, Homework \n4.  Apple, Orange , Pear \n5.  Shoes, Boots, Slippers \n6.  Train, Bus, Tracks \n7.  Computer monitor, Antenna, Television \n8.  Hospital, Bank, Cinema \n9.  Carrot, Eggplant, Rabbit \n10. Cloud, Wind, Rain \n11. Panda, Banana, Monkey \n12. Shirt, Hat, Pants \n13. Kite, Basketball, Tennis \n14. Farmer, Corn, Bread \n15. Shampoo, Hair, Beard \n16. Bridge, Tunnel, Highway \n17. Piano, Violin, Guitar	 \n18. Child, Man	, Woman \n19. Postman, Policeman, Uniform \n20. Letter, Stamp, Postcard"]

survey_items_names = [survey1_names, survey2_names, survey3_names, survey4_names, survey5_names]
survey_items = [survey1_subitems, survey2_items, survey3_items, survey4_items, survey5_items]

number_of_items = len(survey_items)

df_i = pd.DataFrame(columns=[
    'self_1', 'self_2', 'self_3', 'self_4', 'self_5', 'self_6', 'self_7', 'self_8', 'self_9', 'self_10', 

    'creativity_1', 'creativity_2', 'creativity_3', 'creativity_4', 'creativity_5', 'creativity_6', 'creativity_7', 'creativity_8', 'creativity_9', 'creativity_10', 

    'inclusion_1_1', 'inclusion_1_2', 'inclusion_1_3', 'inclusion_1_4', 'inclusion_1_5', 'inclusion_1_6', 'inclusion_1_7', 'inclusion_1_8', 'inclusion_1_9', 'inclusion_1_10',

    'inclusion_2_1', 'inclusion_2_2', 'inclusion_2_3', 'inclusion_2_4', 'inclusion_2_5', 'inclusion_2_6', 'inclusion_2_7', 'inclusion_2_8', 'inclusion_2_9', 'inclusion_2_10',

    'inclusion_3_1', 'inclusion_3_2', 'inclusion_3_3', 'inclusion_3_4', 'inclusion_3_5', 'inclusion_3_6', 'inclusion_3_7', 'inclusion_3_8', 'inclusion_3_9', 'inclusion_3_10',

    'inclusion_4_1', 'inclusion_4_2', 'inclusion_4_3', 'inclusion_4_4', 'inclusion_4_5', 'inclusion_4_6', 'inclusion_4_7', 'inclusion_4_8', 'inclusion_4_9', 'inclusion_4_10',

    'inclusion_5_1', 'inclusion_5_2', 'inclusion_5_3', 'inclusion_5_4', 'inclusion_5_5', 'inclusion_5_6', 'inclusion_5_7', 'inclusion_5_8', 'inclusion_5_9', 'inclusion_5_10',

    'inclusion_6_1', 'inclusion_6_2', 'inclusion_6_3', 'inclusion_6_4', 'inclusion_6_5', 'inclusion_6_6', 'inclusion_6_7', 'inclusion_6_8', 'inclusion_6_9', 'inclusion_6_10',

    'inclusion_7_1', 'inclusion_7_2', 'inclusion_7_3', 'inclusion_7_4', 'inclusion_7_5', 'inclusion_7_6', 'inclusion_7_7', 'inclusion_7_8', 'inclusion_7_9', 'inclusion_7_10',

    'inclusion_8_1', 'inclusion_8_2', 'inclusion_8_3', 'inclusion_8_4', 'inclusion_8_5', 'inclusion_8_6', 'inclusion_8_7', 'inclusion_8_8', 'inclusion_8_9', 'inclusion_8_10',

    'inclusion_9_1', 'inclusion_9_2', 'inclusion_9_3', 'inclusion_9_4', 'inclusion_9_5', 'inclusion_9_6', 'inclusion_9_7', 'inclusion_9_8', 'inclusion_9_9', 'inclusion_9_10',

    'inclusion_10_1', 'inclusion_10_2', 'inclusion_10_3', 'inclusion_10_4', 'inclusion_10_5', 'inclusion_10_6', 'inclusion_10_7', 'inclusion_10_8', 'inclusion_10_9', 'inclusion_10_10',

    'attribution_1_1', 'attribution_1_2', 'attribution_1_3', 'attribution_1_4', 'attribution_1_5', 'attribution_1_6', 'attribution_1_7', 'attribution_1_8', 'attribution_1_9', 'attribution_1_10',

    'attribution_2_1', 'attribution_2_2', 'attribution_2_3', 'attribution_2_4', 'attribution_2_5', 'attribution_2_6', 'attribution_2_7', 'attribution_2_8', 'attribution_2_9', 'attribution_2_10',

    'attribution_3_1', 'attribution_3_2', 'attribution_3_3', 'attribution_3_4', 'attribution_3_5', 'attribution_3_6', 'attribution_3_7', 'attribution_3_8', 'attribution_3_9', 'attribution_3_10',

    'attribution_4_1', 'attribution_4_2', 'attribution_4_3', 'attribution_4_4', 'attribution_4_5', 'attribution_4_6', 'attribution_4_7', 'attribution_4_8', 'attribution_4_9', 'attribution_4_10',

    'attribution_5_1', 'attribution_5_2', 'attribution_5_3', 'attribution_5_4', 'attribution_5_5', 'attribution_5_6', 'attribution_5_7', 'attribution_5_8', 'attribution_5_9', 'attribution_5_10',

    'attribution_6_1', 'attribution_6_2', 'attribution_6_3', 'attribution_6_4', 'attribution_6_5', 'attribution_6_6', 'attribution_6_7', 'attribution_6_8', 'attribution_6_9', 'attribution_6_10',

    'triad_1', 'triad_2', 'triad_3', 'triad_4', 'triad_5', 'triad_6', 'triad_7', 'triad_8', 'triad_9', 'triad_10', 'triad_11', 'triad_12', 'triad_13', 'triad_14', 'triad_15', 'triad_16', 'triad_17', 'triad_18', 'triad_19', 'triad_20'])