# This is different than cognitive_questions.py becauase this uses the origianl inclusion tasks, instead of the ones we created.

import pandas as pd

# task 1
survey1_names = ["self"]
survey1_subitems = ["List 10 specific ways that an average person may choose to identify themselves. Start with ""I am"".\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer."]

# task 2
survey2_names = ["creativity"]
survey2_items = ["Please write 10 words that are as different from each other as possible, in all meanings and uses of the words. Rules:\n1. Only single words.\n2. Only nouns (e.g., things, objects, concepts).\n3. No proper nouns (e.g., no specific people or places).\n4. No specialized vocabulary (e.g., no technical terms).\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer."]

# task 3
survey3_names = ['inclusion_1', 'inclusion_2', 'inclusion_3', 'inclusion_4', 'inclusion_5', 'inclusion_6']
survey3_items = [
   "Suppose that you are the police officer in charge of a case involving a graduate student who murdered a professor (the dead professor was the graduate student's advisor). Why would the graduate student possibly murder his or her advisor? As a police officer, you must establish the motive. I will now list 17 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why the graduate student murdered the professor. \n1. whether or not the professor ever sexually harassed the graduate student. \n2. whether or not the professor drank alcohol. \n3. whether or not the graduate student recently ended a romantic relationship. \n4. the professor's history of sexual abuse by his/her parents. \n5. the graduate student's history of mental disorders. \n6. the professor's history of eating disorders. \n7. whether or not the graduate student and the professor were (or previously had been) engaged in a sexual relationship. \n8. the graduate student's sexual orientation. \n9. whether or not the graduate student ever sexually harassed the professor. \n10. whether the graduate student behaved unreasonably toward the professor. \n11. the graduate student's height and weight. \n12. the professor's sexual orientation. \n13. the way the professor dressed. \n14. whether or not the graduate student drank alcohol. \n15. whether or not the graduate student smoked cigarettes. \n16. whether or not the professor used email regularly. \n17. whether the professor behaved unreasonably toward the graduate student. \nPlease, do not use commas or 'and' to separate out different answers. And please do not lump answers together. For instance, if multiple answers fall under 'irrelevant', do not answer like to following or similar formats: '20, 21, 22 - irrelevant to establishing motive.' Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer. So for the above example, you would have: \n20. Irrelevant. \n21. Irrelevant. \n22 Irrelevant.", 

   "Suppose that you are the police officer in charge of a case involving a graduate student who murdered a professor (the dead professor was the graduate student's advisor). Why would the graduate student possibly murder his or her advisor? As a police officer, you must establish the motive. I will now list 18 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why the graduate student murdered the professor. \n1. whether or not the graduate student was unhelpful. \n2. the professor's height and weight. \n3. whether or not the professor was religious. \n4. whether or not the graduate student came from a dysfunctional family. \n5. whether or not the professor was left-handed. \n6. whether or not the graduate student was far away from his/her hometown. \n7. whether or not the professor was temporarily insane. \n8. whether or not the graduate student liked rock music. \n9. whether or not the professor came from a dysfunctional family. \n10. whether or not the graduate student ever ridiculed the professor in public. \n11. whether or not the professor recently ended a romantic relationship. \n12. whether or not the graduate student was an irritating person. \n13. the professor's history of mental disorders. \n14. whether the professor was introverted or extroverted. \n15. whether or not the professor smoked cigarettes. \n16. whether or not the professor had a history of violence. \n17. whether or not the professor was condescending toward the graduate student. \n18. the graduate student's history of eating disorders.\nPlease, do not use commas or 'and' to separate out different answers. And please do not lump answers together. For instance, if multiple answers fall under 'irrelevant', do not answer like to following or similar formats: '20, 21, 22 - irrelevant to establishing motive.' Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer. So for the above example, you would have: \n20. Irrelevant. \n21. Irrelevant. \n22 Irrelevant.",

   "Suppose that you are the police officer in charge of a case involving a graduate student who murdered a professor (the dead professor was the graduate student's advisor). Why would the graduate student possibly murder his or her advisor? As a police officer, you must establish the motive. I will now list 18 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why the graduate student murdered the professor. \n1. whether or not the professor was an irritating person. \n2. whether the professor had any brothers and sisters. \n3. whether the graduate student liked to attend parties. \n4. whether or not the professor was unhelpful. \n5. whether or not the graduate student liked to watch violent movies. \n6. the graduate student's history of sexual abuse by his/her parents. \n7. the graduate student's IQ score. \n8. whether or not the graduate student was temporarily insane. \n9. the way the graduate student dressed. \n10. whether or not the professor was a vegetarian. \n11. the professor's IQ score. \n12. whether or not the professor could play a musical instrument. \n13. what the graduate student's parents did for a living. \n14. whether the professor preferred to use IBM or Macintosh computers. \n15. what the professor's high school GPA was. \n16. whether the graduate student was introverted or extroverted. \n17. whether or not the professor liked to watch violent movies. \n18. the number of pets the professor owned.\nPlease, do not use commas or 'and' to separate out different answers. And please do not lump answers together. For instance, if multiple answers fall under 'irrelevant', do not answer like to following or similar formats: '20, 21, 22 - irrelevant to establishing motive.' Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer. So for the above example, you would have: \n20. Irrelevant. \n21. Irrelevant. \n22 Irrelevant.",

   "Suppose that you are the police officer in charge of a case involving a graduate student who murdered a professor (the dead professor was the graduate student's advisor). Why would the graduate student possibly murder his or her advisor? As a police officer, you must establish the motive. I will now list 15 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why the graduate student murdered the professor. \n1. the graduate student's zodiac (astrological) sign. \n2. whether the graduate student ever unfairly gave the professor a bad evaluation. \n3. whether or not the graduate student had a history of violence. \n4. whether or not the professor had a webpage. \n5. the professor's favorite food. \n6. whether or not the graduate student lived in a dorm. \n7. the political preferences of the professor. \n8. whether or not the professor ever ridiculed the graduate student in public. \n9. whether or not the graduate student was a drug user. \n10. whether the graduate student had a history of rebelling against persons in authority. \n11. whether the graduate student was a basketball fan. \n12. whether or not the graduate student was religious. \n13. whether the graduate student and the professor had offices on different floors. \n14. whether or not the graduate student used email regularly. \n15. whether or not the graduate student was condescending toward the professor.\nPlease, do not use commas or 'and' to separate out different answers. And please do not lump answers together. For instance, if multiple answers fall under 'irrelevant', do not answer like to following or similar formats: '20, 21, 22 - irrelevant to establishing motive.' Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer. So for the above example, you would have: \n20. Irrelevant. \n21. Irrelevant. \n22 Irrelevant.",

   "Suppose that you are the police officer in charge of a case involving a graduate student who murdered a professor (the dead professor was the graduate student's advisor). Why would the graduate student possibly murder his or her advisor? As a police officer, you must establish the motive. I will now list 16 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why the graduate student murdered the professor. \n1. whether the professor ever unfairly gave the graduate student a bad evaluation. \n2. the number of publications on which the professor and the graduate student had collaborated. \n3. the graduate student's favorite color. \n4. whether or not the professor would have retired soon. \n5. whether the graduate student had any brothers and sisters. \n6. whether or not the professor liked rock music. \n7. what the graduate student's high school GPA was. \n8. whether the professor had a history of abusing his/her authority. \n9. whether or not the graduate student had a webpage. \n10. whether or not the professor had a secretary. \n11. whether the graduate student came to school on a bicycle. \n12. the professor's favorite color. \n13. what the professor was doing on the night in question. \n14. whether or not the graduate student was left-handed. \n15. whether the professor liked to attend parties. \n16. whether the professor was a basketball fan.\nPlease, do not use commas or 'and' to separate out different answers. And please do not lump answers together. For instance, if multiple answers fall under 'irrelevant', do not answer like to following or similar formats: '20, 21, 22 - irrelevant to establishing motive.' Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer. So for the above example, you would have: \n20. Irrelevant. \n21. Irrelevant. \n22 Irrelevant.",

   "Suppose that you are the police officer in charge of a case involving a graduate student who murdered a professor (the dead professor was the graduate student's advisor). Why would the graduate student possibly murder his or her advisor? As a police officer, you must establish the motive. I will now list 13 sentences. Tell me whether each of these is relevant or irrelevant when trying to figure out why the graduate student murdered the professor. \n1. whether the graduate student preferred to use IBM or Macintosh computers. \n2. what the professor's parents did for a living. \n3. whether or not the professor was a drug user. \n4. the political preferences of the graduate student. \n5. the professor's zodiac (astrological) sign. \n6. the graduate student's favorite food. \n7. what the graduate student was doing on the night in question. \n8. whether the professor was far away from his/her hometown. \n9. whether or not the graduate student was a vegetarian. \n10. the number of pets the graduate student owned. \n11. whether the professor came to school on a bicycle. \n12. whether or not the graduate student would have received his/her Ph.D. soon. \n13. whether or not the graduate student could play a musical instrument.\nPlease, do not use commas or 'and' to separate out different answers. And please do not lump answers together. For instance, if multiple answers fall under 'irrelevant', do not answer like to following or similar formats: '20, 21, 22 - irrelevant to establishing motive.' Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer. So for the above example, you would have: \n20. Irrelevant. \n21. Irrelevant. \n22 Irrelevant."

    ]

# task 4
survey4_names = ['attribution_1', 'attribution_2', 'attribution_3', 'attribution_4', 'attribution_5', 'attribution_6']
survey4_items = [
    "Sara Martin is a top executive at a pharmaceutical company that recently developed a new and expensive drug for treating malaria. Shortly after the company developed the drug, there was a significant outbreak of malaria in Africa. In response, Sara Martin decided to donate a lot of medicine to the countries in Africa needing assistance. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Sara Martin (such as her character, attitude, or temperament) influenced her behavior (donatin \nmalaria medicine to countries in Africa needing assistance) \n2. Features of the environment that surround Sara Martin (such as the atmosphere, social norms, or other contextua \nfactors) influenced her behavior (donating malaria medicine to countries in Africa needing assistance) \n3. Sara Martin would have acted differently if her features (such as her character, attitude, or temperament) ha \nbeen different \n4. Sara Martin would have acted differently if features of the environment that surround her (such as th \natmosphere, social norms, or other contextual factors) had been different \n5. The executive, Sara Martin, is conscientious \n6. The executive, Sara Martin, is immoral \n7. The executive, Sara Martin, is evil \n8. The executive, Sara Martin, is honest \n9. The executive, Sara Martin, is respectable \n10. The executive, Sara Martin, is manipulative \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text. \nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer.",
                 
"A doctor at a large hospital, David Conner, provides treatment for many people in the Baltimore area. He specializes in surgeries and performs them often. Recently, a woman underwent routine surgery to treat her stomach ulcers. During the surgery, an avoidable mistake was made and the woman died. David Conner concealed the mistake and told the woman’s family that she died of a heart attack. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of David Conner (such as his character, attitude, or temperament) influenced his behavior (concealing \nan avoidable mistake that caused the death of a patient). \n2. Features of the environment that surround David Conner (such as the atmosphere, social norms, or other \ncontextual factors) influenced his behavior (concealing an avoidable mistake that caused the death of a patient). \n3. David Conner would have acted differently if his features (such as his character, attitude, or temperament) had \nbeen different. \n4. David Conner would have acted differently if features of the environment that surround him (such as the \natmosphere, social norms, or other contextual factors) had been different. \n5. The doctor, David Conner, is conscientious. \n6. The doctor, David Conner, is immoral. \n7. The doctor, David Conner, is evil. \n8. The doctor, David Conner, is honest. \n9. The doctor, David Conner, is respectable. \n10. The doctor, David Conner, is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer.",

"Emma Peterson, a prominent banker at a large bank in Boston, is well known in the local community. The bank lost a lot of money in the stock market, but she did not reveal the loss to the company’s shareholders. Instead, Emma Peterson reported a sizable profit at the annual meeting of the shareholders. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Emma Peterson (such as her character, attitude, or temperament) influenced her behavior (concealing \na sizable loss in the stock market from shareholders). \n2. Features of the environment that surround Emma Peterson (such as the atmosphere, social norms, or other \ncontextual factors) influenced her behavior (concealing a sizable loss in the stock market from shareholders). \n3. Emma Peterson would have acted differently if her features (such as her character, attitude, or temperament) had \nbeen different. \n4. Emma Peterson would have acted differently if features of the environment that surround her (such as the \natmosphere, social norms, or other contextual factors) had been different. \n5. The banker, Emma Peterson, is conscientious. \n6. The banker, Emma Peterson, is immoral. \n7. The banker, Emma Peterson, is evil. \n8. The banker, Emma Peterson, is honest. \n9. The banker, Emma Peterson is respectable. \n10. The banker, Emma Peterson is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer.",

"Steve Jensen is the president of an electric company in Oregon that provides electricity to several large cities in the state. Last year, the winter in Portland was very cold and there were three unexpected snowstorms. Many elderly people in Portland could not afford to pay expensive electricity bills. In response, Steve Jensen decided to provide free electricity to disadvantaged elderly people during the winter months. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Steve Jensen (such as his character, attitude, or temperament) influenced his behavior (providing \nfree electricity to disadvantaged elderly people). \n2. Features of the environment that surround Steve Jensen (such as the atmosphere, social norms, or other \ncontextual factors) influenced his behavior (providing free electricity to disadvantaged elderly people). \n3. Steve Jensen would have acted differently if his features (such as his character, attitude, or temperament) had \nbeen different. \n4. Steve Jensen would have acted differently if features of the environment that surround him (such as the \natmosphere, social norms, or other contextual factors) had been different. \n5. The president, Steve Jensen, is conscientious. \n6. The president, Steve Jensen, is immoral. \n7. The president, Steve Jensen, is evil. \n8. The president, Steve Jensen, is honest. \n9. The president, Steve Jensen is respectable. \n10. The president, Steve Jensen is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer.",

"A pitcher for a professional baseball team, Tom Lyons, lost several games in the beginning of the season. Instead of spending extra time practicing, he used performance-enhancing drugs for the rest of the regular season. Tom Lyons continued to use the drugs, even though the use of performance-enhancing drugs is illegal and considered to be cheating. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Tom Lyons (such as his character, attitude, or temperament) influenced his behavior (using \nperformance-enhancing drugs). \n2. Features of the environment that surround Tom Lyons (such as the atmosphere, social norms, or other contextual \nfactors) influenced his behavior (using performance-enhancing drugs). \n3. Tom Lyons would have acted differently if his features (such as his character, attitude, or temperament) had \nbeen different. \n4. Tom Lyons would have acted differently if features of the environment that surround him (such as the atmosphere, \nsocial norms, or other contextual factors) had been different. \n5. The pitcher, Tom Lyons, is conscientious. \n6. The pitcher, Tom Lyons is immoral. \n7. The pitcher, Tom Lyons is evil. \n8. The pitcher, Tom Lyons is honest. \n9. The pitcher, Tom Lyons, is respectable. \n10. The pitcher, Tom Lyons, is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer.",

"A popular rock singer, Gina Gold, spent twelve months traveling all over the country on a big concert tour. At the end of the tour, she performed four additional charity concerts to raise money for New York City’s youth organizations. Gina Gold raised almost one million dollars for the youth organizations. \nI will now list 10 statements. On a scale from 1 to 7 (where 1 means “strongly disagree” and 7 means “strongly agree”), indicate the extent to which you agree or disagree with each of the following statements. Only use a number from 1 to 7 to indicate your agreement with each statement.  Keep in mind that in some cases, the information may not be enough or cannot be answered with certainty. In these situations, choose the most probable answer, and you must only choose a number. \n1. Features of Gina Gold (such as her character, attitude, or temperament) influenced her behavior (performing \ncharity concerts to raise money for youth organizations). \n2. Features of the environment that surround Gina Gold (such as the atmosphere, social norms, or other contextual \nfactors) influenced her behavior (performing charity concerts to raise money for youth organizations). \n3. Gina Gold would have acted differently if her features (such as her character, attitude, or temperament) had \nbeen different. \n4. Gina Gold would have acted differently if features of the environment that surround her (such as the atmosphere, \nsocial norms, or other contextual factors) had been different. \n5. The singer, Gina Gold, is conscientious. \n6. The singer, Gina Gold, is immoral. \n7. The singer, Gina Gold, is evil. \n8. The singer, Gina Gold, is honest. \n9. The singer, Gina Gold, is respectable. \n10. The singer, Gina Gold, is manipulative. \nAgain, keep in mind that in some cases, the information cannot be answered with certainty. Even so, in these situations, choose the most probable answer. Some answers may be unknown, potentially because of a lack of information. Even so, in these situations, you must only choose the most probable number. Please only provide numbers, and don't give additional text.\nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer."
]

#task 5
survey5_names = ['triad']
survey5_items = ["In the following lists, among the three things listed together, please indicate which two of the three are most closely related. \n1.  Seagull, Sky, Dog \n2.  Black, White, Blue \n3.  Doctor, Teacher, Homework \n4.  Apple, Orange , Pear \n5.  Shoes, Boots, Slippers \n6.  Train, Bus, Tracks \n7.  Computer monitor, Antenna, Television \n8.  Hospital, Bank, Cinema \n9.  Carrot, Eggplant, Rabbit \n10. Cloud, Wind, Rain \n11. Panda, Banana, Monkey \n12. Shirt, Hat, Pants \n13. Kite, Basketball, Tennis \n14. Farmer, Corn, Bread \n15. Shampoo, Hair, Beard \n16. Bridge, Tunnel, Highway \n17. Piano, Violin, Guitar	 \n18. Child, Man	, Woman \n19. Postman, Policeman, Uniform \n20. Letter, Stamp, Postcard \nPlease, do not use commas or ‘and’ to separate out different answers. Instead, put each answer on a separate line in a enumerated list in the form. For instance, each line should first have the line number, followed by a period, followed by a space, then followed by the answer."]

survey_items_names = [survey1_names, survey2_names, survey3_names, survey4_names, survey5_names]
survey_items = [survey1_subitems, survey2_items, survey3_items, survey4_items, survey5_items]

number_of_items = len(survey_items)

df_i = pd.DataFrame(columns=[
    'self_1', 'self_2', 'self_3', 'self_4', 'self_5', 'self_6', 'self_7', 'self_8', 'self_9', 'self_10', 

    'creativity_1', 'creativity_2', 'creativity_3', 'creativity_4', 'creativity_5', 'creativity_6', 'creativity_7', 'creativity_8', 'creativity_9', 'creativity_10', 

    'inclusion_1_1', 'inclusion_1_2', 'inclusion_1_3', 'inclusion_1_4', 'inclusion_1_5', 'inclusion_1_6', 'inclusion_1_7', 'inclusion_1_8', 'inclusion_1_9', 'inclusion_1_10', 'inclusion_1_11', 'inclusion_1_12', 'inclusion_1_13', 'inclusion_1_14', 'inclusion_1_15', 'inclusion_1_16', 'inclusion_1_17',

    'inclusion_2_1', 'inclusion_2_2', 'inclusion_2_3', 'inclusion_2_4', 'inclusion_2_5', 'inclusion_2_6', 'inclusion_2_7', 'inclusion_2_8', 'inclusion_2_9', 'inclusion_2_10', 'inclusion_2_11', 'inclusion_2_12', 'inclusion_2_13', 'inclusion_2_14', 'inclusion_2_15', 'inclusion_2_16', 'inclusion_2_17', 'inclusion_2_18', 

    'inclusion_3_1', 'inclusion_3_2', 'inclusion_3_3', 'inclusion_3_4', 'inclusion_3_5', 'inclusion_3_6', 'inclusion_3_7', 'inclusion_3_8', 'inclusion_3_9', 'inclusion_3_10', 'inclusion_3_11', 'inclusion_3_12', 'inclusion_3_13', 'inclusion_3_14', 'inclusion_3_15', 'inclusion_3_16', 'inclusion_3_17', 'inclusion_3_18', 

    'inclusion_4_1', 'inclusion_4_2', 'inclusion_4_3', 'inclusion_4_4', 'inclusion_4_5', 'inclusion_4_6', 'inclusion_4_7', 'inclusion_4_8', 'inclusion_4_9', 'inclusion_4_10', 'inclusion_4_11', 'inclusion_4_12', 'inclusion_4_13', 'inclusion_4_14', 'inclusion_4_15',

    'inclusion_5_1', 'inclusion_5_2', 'inclusion_5_3', 'inclusion_5_4', 'inclusion_5_5', 'inclusion_5_6', 'inclusion_5_7', 'inclusion_5_8', 'inclusion_5_9', 'inclusion_5_10', 'inclusion_5_11', 'inclusion_5_12', 'inclusion_5_13', 'inclusion_5_14', 'inclusion_5_15', 'inclusion_5_16', 

    'inclusion_6_1', 'inclusion_6_2', 'inclusion_6_3', 'inclusion_6_4', 'inclusion_6_5', 'inclusion_6_6', 'inclusion_6_7', 'inclusion_6_8', 'inclusion_6_9', 'inclusion_6_10', 'inclusion_6_11', 'inclusion_6_12', 'inclusion_6_13', 

    'attribution_1_1', 'attribution_1_2', 'attribution_1_3', 'attribution_1_4', 'attribution_1_5', 'attribution_1_6', 'attribution_1_7', 'attribution_1_8', 'attribution_1_9', 'attribution_1_10',

    'attribution_2_1', 'attribution_2_2', 'attribution_2_3', 'attribution_2_4', 'attribution_2_5', 'attribution_2_6', 'attribution_2_7', 'attribution_2_8', 'attribution_2_9', 'attribution_2_10',

    'attribution_3_1', 'attribution_3_2', 'attribution_3_3', 'attribution_3_4', 'attribution_3_5', 'attribution_3_6', 'attribution_3_7', 'attribution_3_8', 'attribution_3_9', 'attribution_3_10',

    'attribution_4_1', 'attribution_4_2', 'attribution_4_3', 'attribution_4_4', 'attribution_4_5', 'attribution_4_6', 'attribution_4_7', 'attribution_4_8', 'attribution_4_9', 'attribution_4_10',

    'attribution_5_1', 'attribution_5_2', 'attribution_5_3', 'attribution_5_4', 'attribution_5_5', 'attribution_5_6', 'attribution_5_7', 'attribution_5_8', 'attribution_5_9', 'attribution_5_10',

    'attribution_6_1', 'attribution_6_2', 'attribution_6_3', 'attribution_6_4', 'attribution_6_5', 'attribution_6_6', 'attribution_6_7', 'attribution_6_8', 'attribution_6_9', 'attribution_6_10',

    'triad_1', 'triad_2', 'triad_3', 'triad_4', 'triad_5', 'triad_6', 'triad_7', 'triad_8', 'triad_9', 'triad_10', 'triad_11', 'triad_12', 'triad_13', 'triad_14', 'triad_15', 'triad_16', 'triad_17', 'triad_18', 'triad_19', 'triad_20'])